"""Add notebooks

Revision ID: 2c468b48ab41
Revises: 84d5a1b9211a
Create Date: 2026-09-26 21:43:51.971369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c468b48ab41'
down_revision: Union[str, None] = '84d5a1b9211a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notebooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notebooks_id'), 'notebooks', ['id'], unique=False)
    # Batch mode: SQLite cannot ALTER a table to add a foreign key, so alembic
    # copies the table, adds the column and constraint, and moves it back.
    for table in ("decks", "documents"):
        with op.batch_alter_table(table) as batch:
            batch.add_column(sa.Column("notebook_id", sa.Integer(), nullable=True))
            batch.create_index(f"ix_{table}_notebook_id", ["notebook_id"], unique=False)
            batch.create_foreign_key(
                f"fk_{table}_notebook_id", "notebooks", ["notebook_id"], ["id"]
            )
    # ### end Alembic commands ###

    # Give every existing document and deck a home. Without this they are
    # invisible in a notebook-first interface: nothing lists a row whose
    # notebook_id is null.
    connection = op.get_bind()
    has_rows = connection.execute(
        sa.text("SELECT 1 FROM documents UNION SELECT 1 FROM decks LIMIT 1")
    ).first()
    if has_rows:
        connection.execute(
            sa.text(
                "INSERT INTO notebooks (name, description, icon, created_at, updated_at) "
                "VALUES (:name, :description, :icon, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"
            ),
            {
                "name": "Unsorted",
                "description": "Everything that existed before notebooks did.",
                "icon": "📁",
            },
        )
        notebook_id = connection.execute(
            sa.text("SELECT id FROM notebooks WHERE name = 'Unsorted' ORDER BY id DESC LIMIT 1")
        ).scalar()
        connection.execute(
            sa.text("UPDATE documents SET notebook_id = :nid WHERE notebook_id IS NULL"),
            {"nid": notebook_id},
        )
        connection.execute(
            sa.text("UPDATE decks SET notebook_id = :nid WHERE notebook_id IS NULL"),
            {"nid": notebook_id},
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for table in ("documents", "decks"):
        with op.batch_alter_table(table) as batch:
            batch.drop_constraint(f"fk_{table}_notebook_id", type_="foreignkey")
            batch.drop_index(f"ix_{table}_notebook_id")
            batch.drop_column("notebook_id")
    op.drop_index(op.f('ix_notebooks_id'), table_name='notebooks')
    op.drop_table('notebooks')
    # ### end Alembic commands ###
