"""Add study days and awards

Revision ID: 7b5dca85479c
Revises: 2c468b48ab41
Create Date: 2026-09-27 10:25:53.129293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b5dca85479c'
down_revision: Union[str, None] = '2c468b48ab41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detail', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_awards_code')
    )
    op.create_index(op.f('ix_awards_id'), 'awards', ['id'], unique=False)
    op.create_table('study_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('questions_answered', sa.Integer(), nullable=False),
    sa.Column('questions_correct', sa.Integer(), nullable=False),
    sa.Column('canvases_created', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day', name='uq_study_days_day')
    )
    op.create_index(op.f('ix_study_days_day'), 'study_days', ['day'], unique=False)
    op.create_index(op.f('ix_study_days_id'), 'study_days', ['id'], unique=False)
    # ### end Alembic commands ###

    # Rebuild the day record from answers already given. UserProgress keeps a
    # last_attempt_date per question, which is the only history there is, so a
    # day someone studied is a day some question was last attempted. This
    # undercounts days where every question was answered again later, and that
    # is accepted: inventing a richer history would be worse than a modest one.
    connection = op.get_bind()
    rows = connection.execute(
        sa.text(
            "SELECT DATE(last_attempt_date) AS day, COUNT(*) AS answered, "
            "SUM(CASE WHEN last_attempt_correct THEN 1 ELSE 0 END) AS correct "
            "FROM user_progress WHERE last_attempt_date IS NOT NULL GROUP BY DATE(last_attempt_date)"
        )
    ).fetchall()

    for row in rows:
        connection.execute(
            sa.text(
                "INSERT INTO study_days (day, questions_answered, questions_correct, "
                "canvases_created, points, created_at, updated_at) "
                "VALUES (:day, :answered, :correct, 0, :points, "
                "CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)"
            ),
            {
                "day": row[0],
                "answered": row[1] or 0,
                "correct": row[2] or 0,
                "points": (row[2] or 0) * 10,
            },
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_days_id'), table_name='study_days')
    op.drop_index(op.f('ix_study_days_day'), table_name='study_days')
    op.drop_table('study_days')
    op.drop_index(op.f('ix_awards_id'), table_name='awards')
    op.drop_table('awards')
    # ### end Alembic commands ###
