"""Add canvas and canvas routing log

Also adds the two composite indexes that previously existed only in migration
32f25b397e98, which no create_all database ever received.

Revision ID: 84d5a1b9211a
Revises: 64306e156071
Create Date: 2026-09-26 18:07:13.786872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d5a1b9211a'
down_revision: Union[str, None] = '64306e156071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canvases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('request_text', sa.Text(), nullable=False),
    sa.Column('template', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('layout_json', sa.JSON(), nullable=True),
    sa.Column('sources_json', sa.JSON(), nullable=False),
    sa.Column('routing_confidence', sa.Float(), nullable=True),
    sa.Column('chosen_by_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_canvases_document', 'canvases', ['document_id'], unique=False)
    op.create_index(op.f('ix_canvases_id'), 'canvases', ['id'], unique=False)
    op.create_table('canvas_routing_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canvas_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('request_text', sa.Text(), nullable=False),
    sa.Column('chosen_template', sa.String(length=40), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('probabilities_json', sa.JSON(), nullable=True),
    sa.Column('shape_signals_json', sa.JSON(), nullable=True),
    sa.Column('granularity_index', sa.Integer(), nullable=True),
    sa.Column('auto_applied', sa.Boolean(), nullable=False),
    sa.Column('user_override', sa.String(length=40), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['canvas_id'], ['canvases.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canvas_routing_log_id'), 'canvas_routing_log', ['id'], unique=False)
    # The legacy decks / deck_questions tables that autogenerate wanted to drop
    # here are deliberately left alone. They predate the rename to tests (ADR
    # 005) and may still hold a user's data; removing them is its own decision,
    # not a side effect of adding the canvas.
    op.create_index('idx_questions_document_difficulty', 'questions', ['document_id', 'difficulty'], unique=False)
    op.create_index('idx_user_progress_question_review', 'user_progress', ['question_id', 'next_review_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_progress_question_review', table_name='user_progress')
    op.drop_index('idx_questions_document_difficulty', table_name='questions')
    op.drop_index(op.f('ix_canvas_routing_log_id'), table_name='canvas_routing_log')
    op.drop_table('canvas_routing_log')
    op.drop_index(op.f('ix_canvases_id'), table_name='canvases')
    op.drop_index('idx_canvases_document', table_name='canvases')
    op.drop_table('canvases')
    # ### end Alembic commands ###
