from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session, joinedload
from typing import List, Optional
from pydantic import BaseModel, ConfigDict

from ..utils.cache import invalidate_stats_cache
from ..db import get_db
from ..models.question import Question, QuestionOption
from ..models.deck import Deck, DeckQuestion
from ..models.tag import Tag
from ..services.ai import curation
from ..services.typesafe_key import typesafe_key as _typesafe_key

router = APIRouter()

FLASHCARD_PLACEHOLDER = "Flip to see answer"


class QuestionOptionCreate(BaseModel):
    """Schema for creating a question option"""

    text: str
    is_correct: bool

    model_config = ConfigDict(json_schema_extra={"example": {"text": "Paris", "is_correct": True}})


class CreateQuestionRequest(BaseModel):
    """Schema for creating a new question"""

    question_text: str
    options: List[QuestionOptionCreate]
    explanation: str = ""
    difficulty: str = "medium"
    deck_id: Optional[int] = None
    document_id: Optional[int] = None

    model_config = ConfigDict(json_schema_extra={
        "example": {
            "question_text": "What is the capital of France?",
            "options": [
                {"text": "Paris", "is_correct": True},
                {"text": "London", "is_correct": False},
                {"text": "Berlin", "is_correct": False},
                {"text": "Madrid", "is_correct": False},
            ],
            "explanation": "Paris is the capital and largest city of France.",
            "difficulty": "easy",
            "deck_id": 1,
            "document_id": 5,
        }
    })


@router.post(
    "/",
    summary="Create a new question",
    description="Create a new multiple-choice question manually with custom options and explanation.",
    response_description="The created question with all options",
    responses={
        200: {
            "description": "Question created successfully",
            "content": {
                "application/json": {
                    "example": {
                        "id": 123,
                        "document_id": 5,
                        "question_text": "What is the capital of France?",
                        "options": [
                            {"id": 1, "text": "Paris", "option": "A", "is_correct": True},
                            {"id": 2, "text": "London", "option": "B", "is_correct": False},
                            {"id": 3, "text": "Berlin", "option": "C", "is_correct": False},
                            {"id": 4, "text": "Madrid", "option": "D", "is_correct": False},
                        ],
                        "explanation": "Paris is the capital and largest city of France.",
                        "difficulty": "easy",
                        "source_reference": {"manual": True},
                        "created_at": "2024-01-15T10:30:00Z",
                    }
                }
            },
        },
        400: {
            "description": "Validation error",
            "content": {
                "application/json": {
                    "examples": {
                        "too_few_options": {
                            "summary": "Too few options",
                            "value": {"detail": "Question must have at least 2 options"},
                        },
                        "wrong_correct_count": {
                            "summary": "Wrong number of correct answers",
                            "value": {"detail": "Question must have exactly one correct option"},
                        },
                    }
                }
            },
        },
    },
)
async def create_question(request: CreateQuestionRequest, db: Session = Depends(get_db)):
    """
    Create a new multiple-choice question manually.

    This endpoint allows you to create custom questions with your own text, options,
    and explanations. Questions can optionally be associated with a document or deck.

    **Validation Rules:**
    - Must have at least 2 options (typically 4 for multiple choice)
    - Exactly one option must be marked as correct
    - Question text is required
    - Difficulty must be one of: easy, medium, hard

    **Use Cases:**
    - Creating custom study questions
    - Adding questions not generated by AI
    - Building question banks manually
    - Testing and development
    """

    # Validate options
    if len(request.options) < 2:
        raise HTTPException(status_code=400, detail="Question must have at least 2 options")

    correct_count = sum(1 for opt in request.options if opt.is_correct)
    if correct_count != 1:
        raise HTTPException(status_code=400, detail="Question must have exactly one correct option")

    deck = None
    if request.deck_id is not None:
        deck = db.query(Deck).filter(Deck.id == request.deck_id).first()
        if deck is None:
            raise HTTPException(status_code=404, detail="Deck not found")

    # Create question
    question = Question(
        document_id=request.document_id,
        question_text=request.question_text,
        explanation=request.explanation,
        difficulty=request.difficulty,
        source_reference={"manual": True},
    )
    db.add(question)
    db.flush()

    # Add to deck if specified
    if deck is not None:
        next_order = max((link.order for link in deck.deck_questions), default=-1) + 1
        deck.deck_questions.append(DeckQuestion(question_id=question.id, order=next_order))

    # Create options
    for i, opt_data in enumerate(request.options):
        option = QuestionOption(
            question_id=question.id,
            option_text=opt_data.text,
            is_correct=opt_data.is_correct,
            order=i,
        )
        db.add(option)

    db.commit()
    invalidate_stats_cache()
    db.refresh(question)

    return format_question(question)


@router.get(
    "/{question_id}",
    summary="Get a question by ID",
    description="Retrieve a single question with all its options and metadata.",
    response_description="The requested question",
    responses={
        200: {
            "description": "Question found",
            "content": {
                "application/json": {
                    "example": {
                        "id": 123,
                        "document_id": 5,
                        "question_text": "What is the capital of France?",
                        "options": [
                            {"id": 1, "text": "Paris", "option": "A", "is_correct": True},
                            {"id": 2, "text": "London", "option": "B", "is_correct": False},
                        ],
                        "explanation": "Paris is the capital of France.",
                        "difficulty": "easy",
                        "source_reference": {"page": 5, "section": "Geography"},
                        "created_at": "2024-01-15T10:30:00Z",
                    }
                }
            },
        },
        404: {
            "description": "Question not found",
            "content": {"application/json": {"example": {"detail": "Question not found"}}},
        },
    },
)
async def get_question(question_id: int, db: Session = Depends(get_db)):
    """
    Retrieve a single question by its ID.

    Returns the complete question including all options, explanation, difficulty level,
    and source reference information. Options are returned in order (A, B, C, D).
    """
    # Eagerly load options to avoid N+1 query
    question = (
        db.query(Question)
        .options(joinedload(Question.options))
        .filter(Question.id == question_id)
        .first()
    )

    if not question:
        raise HTTPException(status_code=404, detail="Question not found")

    return format_question(question)


@router.get(
    "/document/{document_id}",
    summary="Get questions for a document",
    description="Retrieve all questions generated from a specific document with optional filtering.",
    response_description="List of questions",
    responses={
        200: {
            "description": "List of questions (may be empty)",
            "content": {
                "application/json": {
                    "example": [
                        {
                            "id": 123,
                            "document_id": 5,
                            "question_text": "What is the capital of France?",
                            "options": [
                                {"id": 1, "text": "Paris", "option": "A", "is_correct": True},
                                {"id": 2, "text": "London", "option": "B", "is_correct": False},
                            ],
                            "explanation": "Paris is the capital of France.",
                            "difficulty": "easy",
                            "source_reference": {"page": 5},
                            "created_at": "2024-01-15T10:30:00Z",
                        }
                    ]
                }
            },
        }
    },
)
async def get_document_questions(
    document_id: int,
    skip: int = 0,
    limit: int = 100,
    difficulty: Optional[str] = None,
    db: Session = Depends(get_db),
):
    """
    Get all questions generated from a specific document.

    Supports pagination and filtering by difficulty level. Questions are returned
    in the order they were created.

    **Query Parameters:**
    - `skip`: Number of questions to skip (for pagination)
    - `limit`: Maximum number of questions to return (default: 100, max: 100)
    - `difficulty`: Filter by difficulty level (easy, medium, hard)

    **Use Cases:**
    - Reviewing all questions from a document
    - Building study sessions from specific documents
    - Filtering questions by difficulty
    """
    # Use composite index for document_id + difficulty filtering
    query = (
        db.query(Question)
        .options(joinedload(Question.options))
        .filter(Question.document_id == document_id)
    )

    if difficulty:
        query = query.filter(Question.difficulty == difficulty)

    questions = query.offset(skip).limit(limit).all()

    return [format_question(q) for q in questions]


@router.delete(
    "/{question_id}",
    summary="Delete a question",
    description="Permanently delete a question and all its options.",
    response_description="Deletion confirmation",
    responses={
        200: {
            "description": "Question deleted successfully",
            "content": {
                "application/json": {"example": {"message": "Question deleted successfully"}}
            },
        },
        404: {
            "description": "Question not found",
            "content": {"application/json": {"example": {"detail": "Question not found"}}},
        },
    },
)
async def delete_question(question_id: int, db: Session = Depends(get_db)):
    """
    Delete a question permanently.

    This will also delete all associated options and remove the question from any decks.
    This operation cannot be undone.

    **Warning:** Deleting a question will also delete any user progress associated with it.
    """
    question = db.query(Question).filter(Question.id == question_id).first()

    if not question:
        raise HTTPException(status_code=404, detail="Question not found")

    db.delete(question)
    db.commit()
    invalidate_stats_cache()

    return {"message": "Question deleted successfully"}


def format_question(question: Question) -> dict:
    """Format question for API response"""
    return {
        "id": question.id,
        "document_id": question.document_id,
        "question_text": question.question_text,
        "options": [
            {
                "id": opt.id,
                "text": opt.option_text,
                "option": chr(65 + opt.order),  # A, B, C, D
                "is_correct": opt.is_correct,
            }
            for opt in sorted(question.options, key=lambda x: x.order)
        ],
        "explanation": question.explanation,
        "difficulty": question.difficulty,
        "source_reference": question.source_reference,
        "created_at": question.created_at,
    }


# ---------------------------------------------------------------------------
# System One features: grading, tagging and duplicate detection.
#
# All three are judgments rather than generation, so they run on Jev and need no
# LLM provider. Each returns a usable result when Jev is unavailable rather than
# failing the request.
# ---------------------------------------------------------------------------


class GradeAnswerRequest(BaseModel):
    """A written answer to grade against the expected one."""

    answer: str


def _has_flashcard_answer(question: Question) -> bool:
    """Whether the single placeholder option has a stored back text."""
    return (
        len(question.options) == 1
        and question.options[0].option_text == FLASHCARD_PLACEHOLDER
        and bool(question.explanation)
    )


def expected_answer(question: Question) -> str:
    """The flashcard back or correct option used to grade a written answer."""
    if _has_flashcard_answer(question):
        return question.explanation
    return next((option.option_text for option in question.options if option.is_correct), "")


def require_typesafe_key(db: Session) -> str:
    """The TypeSafe key, or a 503 explaining that grading needs one."""
    api_key = _typesafe_key(db)
    if not api_key:
        raise HTTPException(
            status_code=503,
            detail="Grading needs a TypeSafe API key. Add one in Settings.",
        )
    return api_key


def grade_to_response(question_text: str, expected: str, answer: str, api_key: str) -> dict:
    """Call the grader and shape its result. Touches no database state.

    Kept free of the session so callers on the event loop can run it in a
    thread without sharing the session across threads.
    """
    grade = curation.grade_answer(
        question_text=question_text,
        expected_answer=expected,
        given_answer=answer,
        api_key=api_key,
    )

    if not grade.checked:
        raise HTTPException(status_code=503, detail="The grading service is unavailable.")

    return {
        "quality": grade.quality,
        "passed": grade.passed,
        "is_correct": round(grade.is_correct, 3),
        "missed_key_point": round(grade.missed_key_point, 3),
        "expected_answer": expected,
    }


def key_points(question: Question) -> List[str]:
    """What a good explanation of this question should convey.

    The correct answer first, then the sentences of the stored explanation.
    """
    points = [expected_answer(question)]
    if not _has_flashcard_answer(question):
        points += curation.split_sentences(question.explanation or "")
    return [point for point in points if point]


def source_passage(question: Question) -> str:
    """The stored passage, or the short citation for older questions."""
    reference = question.source_reference or {}
    return reference.get("passage") or (reference.get("text") or "").removesuffix("...")


def hint_candidates(question: Question) -> List[str]:
    """Sentences a hint may be copied from: the explanation, then the source passage."""
    source = source_passage(question)
    return curation.split_sentences(question.explanation or "") + curation.split_sentences(source)


def fallback_hint(grade: dict) -> str:
    """A hint from the grade itself, for when no sentence can be selected."""
    if grade.get("missed_key_point", 0) >= 0.5:
        return "Your answer leaves out the main point the question is after. What is it really asking?"
    if grade.get("is_correct", 0) >= 0.5:
        return "You are on the right track. Be more specific."
    return "That is not it. Reread the question and think about which idea it depends on."


def hint_for(question_text: str, expected: str, candidates: List[str], grade: dict, api_key: str) -> str:
    """A selected hint, or one built from the grade. Touches no database state."""
    return curation.select_hint(question_text, expected, candidates, api_key) or fallback_hint(grade)


def explanation_to_response(
    question_text: str, points: List[str], explanation: str, api_key: str, source: str = ""
) -> dict:
    """Review an explanation and shape the result. Touches no database state."""
    review = curation.review_explanation(question_text, points, explanation, api_key, source=source)
    if not review.checked:
        raise HTTPException(status_code=503, detail="The review service is unavailable.")
    return {
        "quality": review.quality,
        "passed": review.passed,
        "sentences": review.sentences,
        "points": review.points,
        "points_covered": sum(point["covered"] for point in review.points),
        "points_total": len(review.points),
    }


@router.post("/{question_id}/grade")
def grade_written_answer(
    question_id: int, request: GradeAnswerRequest, db: Session = Depends(get_db)
):
    """Grade a free-text answer and return a quality SM-2 can consume.

    The quality is a 0 to 5 Score rather than a yes/no, because the scheduler
    wants degree: an answer that is right but vague should not be scheduled the
    same as one that is right and precise.
    """
    question = db.query(Question).filter(Question.id == question_id).first()
    if not question:
        raise HTTPException(status_code=404, detail="Question not found")

    api_key = require_typesafe_key(db)
    return grade_to_response(
        question.question_text, expected_answer(question), request.answer, api_key
    )


@router.get("/{question_id}/suggested-tags")
def suggested_tags(question_id: int, db: Session = Depends(get_db)):
    """Which of the existing tags apply to this question, best first.

    Only tags that already exist are offered, so the vocabulary stays controlled
    instead of drifting with every generation. Tags already on the question are
    not judged at all. Nothing is applied here: the user accepts each one.

    `reason` is set whenever the list is empty for a reason other than "no tag
    fits", so the interface can say why.
    """
    question = db.query(Question).filter(Question.id == question_id).first()
    if not question:
        raise HTTPException(status_code=404, detail="Question not found")

    applied = {tag.id for tag in question.tags}
    candidates = [tag for tag in db.query(Tag).order_by(Tag.name).all() if tag.id not in applied]

    if not candidates:
        reason = "Every tag is already on this card." if applied else "Create a tag first."
        return {"suggested": [], "reason": reason}

    api_key = _typesafe_key(db)
    if not api_key:
        return {"suggested": [], "reason": "Tag suggestions need a TypeSafe API key."}

    scores = curation.score_tags(
        question={
            "question_text": question.question_text,
            "explanation": question.explanation,
        },
        available_tags=[tag.name for tag in candidates],
        api_key=api_key,
    )
    if scores is None:
        return {"suggested": [], "reason": "The suggestion service is unavailable."}

    suggested = sorted(
        (
            {"id": tag.id, "name": tag.name, "color": tag.color,
             "probability": round(scores[tag.name], 3)}
            for tag in candidates
            if scores.get(tag.name, 0.0) >= curation.TAG_THRESHOLD
        ),
        key=lambda item: item["probability"],
        reverse=True,
    )
    return {"suggested": suggested}


class DuplicateCheckRequest(BaseModel):
    """Question ids to compare against one another."""

    question_ids: List[int]


@router.post("/duplicates")
def find_duplicate_questions(request: DuplicateCheckRequest, db: Session = Depends(get_db)):
    """Find questions in the set that test the same thing as an earlier one.

    The earlier question of each pair is kept. Nothing is deleted here: the
    caller decides what to do with the pairs.
    """
    if len(request.question_ids) < 2:
        return {"duplicates": []}

    questions = (
        db.query(Question).filter(Question.id.in_(request.question_ids)).all()
    )
    # Preserve the caller's order, since "keep the earlier one" depends on it.
    by_id = {question.id: question for question in questions}
    ordered = [by_id[qid] for qid in request.question_ids if qid in by_id]

    api_key = _typesafe_key(db)
    if not api_key:
        return {"duplicates": [], "reason": "No TypeSafe API key configured."}

    pairs = curation.find_duplicates(
        questions=[{"question_text": question.question_text} for question in ordered],
        api_key=api_key,
    )

    return {
        "duplicates": [
            {
                "keep": ordered[pair.kept_index].id,
                "duplicate": ordered[pair.duplicate_index].id,
                "probability": round(pair.probability, 3),
            }
            for pair in pairs
        ]
    }
