from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session, joinedload
from typing import List, Optional
from pydantic import BaseModel

from ..db import get_db
from ..models.question import Question, QuestionOption

router = APIRouter()


class QuestionOptionCreate(BaseModel):
    """Schema for creating a question option"""

    text: str
    is_correct: bool

    class Config:
        schema_extra = {"example": {"text": "Paris", "is_correct": True}}


class CreateQuestionRequest(BaseModel):
    """Schema for creating a new question"""

    question_text: str
    options: List[QuestionOptionCreate]
    explanation: str = ""
    difficulty: str = "medium"
    deck_id: Optional[int] = None
    document_id: Optional[int] = None

    class Config:
        schema_extra = {
            "example": {
                "question_text": "What is the capital of France?",
                "options": [
                    {"text": "Paris", "is_correct": True},
                    {"text": "London", "is_correct": False},
                    {"text": "Berlin", "is_correct": False},
                    {"text": "Madrid", "is_correct": False},
                ],
                "explanation": "Paris is the capital and largest city of France.",
                "difficulty": "easy",
                "deck_id": 1,
                "document_id": 5,
            }
        }


@router.post(
    "/",
    summary="Create a new question",
    description="Create a new multiple-choice question manually with custom options and explanation.",
    response_description="The created question with all options",
    responses={
        200: {
            "description": "Question created successfully",
            "content": {
                "application/json": {
                    "example": {
                        "id": 123,
                        "document_id": 5,
                        "question_text": "What is the capital of France?",
                        "options": [
                            {"id": 1, "text": "Paris", "option": "A", "is_correct": True},
                            {"id": 2, "text": "London", "option": "B", "is_correct": False},
                            {"id": 3, "text": "Berlin", "option": "C", "is_correct": False},
                            {"id": 4, "text": "Madrid", "option": "D", "is_correct": False},
                        ],
                        "explanation": "Paris is the capital and largest city of France.",
                        "difficulty": "easy",
                        "source_reference": {"manual": True},
                        "created_at": "2024-01-15T10:30:00Z",
                    }
                }
            },
        },
        400: {
            "description": "Validation error",
            "content": {
                "application/json": {
                    "examples": {
                        "too_few_options": {
                            "summary": "Too few options",
                            "value": {"detail": "Question must have at least 2 options"},
                        },
                        "wrong_correct_count": {
                            "summary": "Wrong number of correct answers",
                            "value": {"detail": "Question must have exactly one correct option"},
                        },
                    }
                }
            },
        },
    },
)
async def create_question(request: CreateQuestionRequest, db: Session = Depends(get_db)):
    """
    Create a new multiple-choice question manually.

    This endpoint allows you to create custom questions with your own text, options,
    and explanations. Questions can optionally be associated with a document or deck.

    **Validation Rules:**
    - Must have at least 2 options (typically 4 for multiple choice)
    - Exactly one option must be marked as correct
    - Question text is required
    - Difficulty must be one of: easy, medium, hard

    **Use Cases:**
    - Creating custom study questions
    - Adding questions not generated by AI
    - Building question banks manually
    - Testing and development
    """

    # Validate options
    if len(request.options) < 2:
        raise HTTPException(status_code=400, detail="Question must have at least 2 options")

    correct_count = sum(1 for opt in request.options if opt.is_correct)
    if correct_count != 1:
        raise HTTPException(status_code=400, detail="Question must have exactly one correct option")

    # Create question
    question = Question(
        document_id=request.document_id,
        question_text=request.question_text,
        explanation=request.explanation,
        difficulty=request.difficulty,
        source_reference={"manual": True},
    )
    db.add(question)
    db.flush()

    # Add to deck if specified
    if request.deck_id:
        from ..models.test import Test

        deck = db.query(Test).filter(Test.id == request.deck_id).first()
        if deck:
            deck.questions.append(question)

    # Create options
    for i, opt_data in enumerate(request.options):
        option = QuestionOption(
            question_id=question.id,
            option_text=opt_data.text,
            is_correct=opt_data.is_correct,
            order=i,
        )
        db.add(option)

    db.commit()
    db.refresh(question)

    return format_question(question)


@router.get(
    "/{question_id}",
    summary="Get a question by ID",
    description="Retrieve a single question with all its options and metadata.",
    response_description="The requested question",
    responses={
        200: {
            "description": "Question found",
            "content": {
                "application/json": {
                    "example": {
                        "id": 123,
                        "document_id": 5,
                        "question_text": "What is the capital of France?",
                        "options": [
                            {"id": 1, "text": "Paris", "option": "A", "is_correct": True},
                            {"id": 2, "text": "London", "option": "B", "is_correct": False},
                        ],
                        "explanation": "Paris is the capital of France.",
                        "difficulty": "easy",
                        "source_reference": {"page": 5, "section": "Geography"},
                        "created_at": "2024-01-15T10:30:00Z",
                    }
                }
            },
        },
        404: {
            "description": "Question not found",
            "content": {"application/json": {"example": {"detail": "Question not found"}}},
        },
    },
)
async def get_question(question_id: int, db: Session = Depends(get_db)):
    """
    Retrieve a single question by its ID.

    Returns the complete question including all options, explanation, difficulty level,
    and source reference information. Options are returned in order (A, B, C, D).
    """
    # Eagerly load options to avoid N+1 query
    question = (
        db.query(Question)
        .options(joinedload(Question.options))
        .filter(Question.id == question_id)
        .first()
    )

    if not question:
        raise HTTPException(status_code=404, detail="Question not found")

    return format_question(question)


@router.get(
    "/document/{document_id}",
    summary="Get questions for a document",
    description="Retrieve all questions generated from a specific document with optional filtering.",
    response_description="List of questions",
    responses={
        200: {
            "description": "List of questions (may be empty)",
            "content": {
                "application/json": {
                    "example": [
                        {
                            "id": 123,
                            "document_id": 5,
                            "question_text": "What is the capital of France?",
                            "options": [
                                {"id": 1, "text": "Paris", "option": "A", "is_correct": True},
                                {"id": 2, "text": "London", "option": "B", "is_correct": False},
                            ],
                            "explanation": "Paris is the capital of France.",
                            "difficulty": "easy",
                            "source_reference": {"page": 5},
                            "created_at": "2024-01-15T10:30:00Z",
                        }
                    ]
                }
            },
        }
    },
)
async def get_document_questions(
    document_id: int,
    skip: int = 0,
    limit: int = 100,
    difficulty: Optional[str] = None,
    db: Session = Depends(get_db),
):
    """
    Get all questions generated from a specific document.

    Supports pagination and filtering by difficulty level. Questions are returned
    in the order they were created.

    **Query Parameters:**
    - `skip`: Number of questions to skip (for pagination)
    - `limit`: Maximum number of questions to return (default: 100, max: 100)
    - `difficulty`: Filter by difficulty level (easy, medium, hard)

    **Use Cases:**
    - Reviewing all questions from a document
    - Building study sessions from specific documents
    - Filtering questions by difficulty
    """
    # Use composite index for document_id + difficulty filtering
    query = (
        db.query(Question)
        .options(joinedload(Question.options))
        .filter(Question.document_id == document_id)
    )

    if difficulty:
        query = query.filter(Question.difficulty == difficulty)

    questions = query.offset(skip).limit(limit).all()

    return [format_question(q) for q in questions]


@router.delete(
    "/{question_id}",
    summary="Delete a question",
    description="Permanently delete a question and all its options.",
    response_description="Deletion confirmation",
    responses={
        200: {
            "description": "Question deleted successfully",
            "content": {
                "application/json": {"example": {"message": "Question deleted successfully"}}
            },
        },
        404: {
            "description": "Question not found",
            "content": {"application/json": {"example": {"detail": "Question not found"}}},
        },
    },
)
async def delete_question(question_id: int, db: Session = Depends(get_db)):
    """
    Delete a question permanently.

    This will also delete all associated options and remove the question from any decks.
    This operation cannot be undone.

    **Warning:** Deleting a question will also delete any user progress associated with it.
    """
    question = db.query(Question).filter(Question.id == question_id).first()

    if not question:
        raise HTTPException(status_code=404, detail="Question not found")

    db.delete(question)
    db.commit()

    return {"message": "Question deleted successfully"}


def format_question(question: Question) -> dict:
    """Format question for API response"""
    return {
        "id": question.id,
        "document_id": question.document_id,
        "question_text": question.question_text,
        "options": [
            {
                "id": opt.id,
                "text": opt.option_text,
                "option": chr(65 + opt.order),  # A, B, C, D
                "is_correct": opt.is_correct,
            }
            for opt in sorted(question.options, key=lambda x: x.order)
        ],
        "explanation": question.explanation,
        "difficulty": question.difficulty,
        "source_reference": question.source_reference,
        "created_at": question.created_at,
    }
